docs: readme yapısı ve içeriği hazırlandı
Kodluyoruz/discord-points-bot pull request #36
Opened 2023-09-26 19:16 UTC by selmakoksal

2023-09-26 19:42 UTC, furkanulutas0 requested changes

2023-09-26 19:42 UTC, furkanulutas0 commented on README.md
> +Kodluyoruz ekibi ve Kodluyoruz Açık Kaynak gönüllüleri tarafından hazırlanmış Discord puan botu, Discord sunucularında kullanılmak üzere özelleştirilebilir,
8-12 satır arası tek satır paragraf haline getirilebilirse iyi olur.

2023-09-26 19:42 UTC, furkanulutas0 commented on README.md
> +### Versiyonlar (Ops)
22. satırda Versiyonlar kısmında (Ops) kaldırılmalı

2023-09-26 21:33 UTC, furkanulutas0 approved these changes
💯

2023-09-27 16:19 UTC, Onur-Morkoc approved these changes

2023-09-27 22:59 UTC, merged